### ISSUE TITLE
include BEL namespace information in graph metadata

### ISSUE THREAD

**Issue by ncatlett** [jsongraph/bel-jsongraph-format#1]
It would be helpful to include BEL namespace information (i.e., version and definitions of prefixes) in the graph metadata. A standard format is needed.

**Comment by abargnesi** [comment]
:+1:

I vote for `graph.metadata.references`. An example use of _references_ is in [evidence schema](http://next.belframework.org/schema/evidence.schema.json) for openbel-server.

FYI, I think this is a major version bump (i.e. 3.0). We could be changing the schema of `graph.metadata.references` if that key is already in use for some user data.

**Comment by wshayes** [comment]
Added a references section in the nanopub (old evidence) part of the edge metadata as suggested by Tony.
